### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Mitsukiii** [mdbell/Noexes#10]
Some things would be neat:

- Remote Control

Like the HID Patches on 3ds to Send Controls via Memory Writes.

- a shorten Class

Reading/Writing via Classes to make Bots/Remote Controls.

- Ingame Address/Hex Viewer

**Comment by mdbell** [comment]
Your remote control idea and in-game memory viewer are a little outside the scope of this project. The remote controller idea is a neat one though and it would be pretty cool to see it as a standalone sysmodule. While an in-game memory viewer is possible it would increase the overhead of noexs, and I personally want to keep resource usage to a minimum.

Also what do you mean a shorten class? If you want to write your own software that interfaces with the console you already can! Look into the Debugger class (iirc it's in the core package, on mobile rn so I can't check)

**Comment by mdbell** [comment]
Again you can already use noexs as a library. Just use the Debugger class:
https://github.com/mdbell/Noexes/blob/master/client/src/me/mdbell/noexs/core/Debugger.java#L17

Here's some sample code (has no imports or error checking, but you should be able to see how to use it):
```
public static void main(String[] args) {
    Socket sock = new Socket("192.168.200.150", 7331); // open the TCP socket to connect to the console with
    //create the Connection (eventually when USB is supported there will also be a USBConnection, thus the usage of an interface)
    IConnection conn = new SocketConnection(sock);
    
    //create the Debugger instance
    Debugger debug = new Debugger(conn);
    
    //now you can interact with the debugger
    
    //you should always call getStatus before issuing any other commands, it will never change and it checks to see if the remote
    //version is compatable with the local version (if not it will raise an exception)
    System.out.println(debug.getStatus());
    
    //pause the console
    Result res = debug.pause();
    
    if(!res.succeeded()){
        // unable to pause, log the result and exit
        System.out.println(res);
        return;
    }
    
    //address to poke
    long address = 0xDEADBEEF;
    //value to poke
    long value = 0xAB;
    
    //poke one byte of memory
    debug.poke(DataType.BYTE, address, value);
    
    //ideally you would also error check this like pausing, but you can do that :P
    debug.resume();
}
```

And I agree that an ingame menu would be neat, but we're currently running custom sysmodules in a fairly restricted manner, last I checked all custom ones share the same pool of memory, and something like that would increase memory usage a fair amount (and make noxs incompatable with other sysmodules that use a fair amount of ram, like LayeredFS). Instead I could allow noexs to implement itself as a service on the console and allow a usermode app to interact with it, but said usermode app wouldn't actually be a part of noexs. It is something to think about.
