### ISSUE TITLE
Problem 1.1.2

### ISSUE THREAD

**Issue by Talixme** [mdbell/Noexes#16]
In this version after a connect,attach, if you detach ,disconnect ,close the game and open the game again, the game doesnt load anymore and you have to restart. Other versions works fine.

Thanks.

**Comment by mdbell** [comment]
Is this only with client version 1.1.2? And do you have any pointers being looked up (in the watchlist, or the tools tab)?

**Comment by Talixme** [comment]
Yes, only on client version 1.1.2, without pointers or any codes on the watchlist

**Comment by mdbell** [comment]
Any chance you could run the client from the terminal/command line?

The command would be:
```
java -jar JNoexsClient.jar
```

And then copy/paste the output after causing the freeze.

**Comment by mdbell** [comment]
Oh and I doubt that it would change anything, can you still test with the hotfix I posted around an hour ago?

**Comment by Talixme** [comment]
With the new hotfix version its working fine again, THANKS!!!!
