### ISSUE TITLE
sleep mode 6.x

### ISSUE THREAD

**Issue by bad1dea** [mdbell/Noexes#18]
hey experiencing sleep mode issues and adding secmon=modules/atmosphere/exosphere.bin as suggested else where isn't correcting it.

[Noexs]
kip1=modules/nsdebugger/loader.kip
kip1=modules/newfirm/*
kip1=noexs.kip1
secmon=modules/atmosphere/exosphere.bin
kip1patch=nosigchk
atmosphere=1
debugmode=1
fullsvcperm=1

**Comment by mdbell** [comment]
This issue seems to overlap with other sysmodules that use debugmode, like sys-netcheat:
https://github.com/jakibaki/sys-netcheat/issues/22

Also you probably want to follow along with the associated hekate issue:
https://github.com/CTCaer/hekate/issues/119

**Comment by mdbell** [comment]
Oh and with Atmosphere providing offical builds could you try loading Noexes with their latest ones?

**Comment by jakibaki** [comment]
>Oh and with Atmosphere providing offical builds could you try loading Noexes with their latest ones?

Does atmosphere ship with the debugmode-patches?
