### ISSUE TITLE
Error: Could not find or load main class me.mdbell.noexs.ui.NoexsApplication with JDK 11

### ISSUE THREAD

**Issue by rushairer** [mdbell/Noexes#19]
I get
```
Error: Could not find or load main class me.mdbell.noexs.ui.NoexsApplication
```
with JDK 11 both in Windows and MacOS,

When I use this command
```
java -jar JNoexsClient.jar
```

Thanks!

**Comment by mleeneg** [comment]
I had lots of problems when I tried it. Java 11 does not work with opening the client.
Go [HERE](https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase10-4425482.html) to get Java SE Development Kit 10.0.2. 
For Win 10: 
1. Install jdk-10.0.2_windows-x64_bin.exe
2. Open Control Panel
3. Click on System
4. Click on Advance system settings on the left side 
5. Click on Environment Variables.
6. Select Path in System Variables.
7. Click on Edit.
8. Click on New
9. Type in directory of Java 10.0.2 bin (Example: Mine is C:\Program Files\Java\jre-10.0.2\bin)
**Note: Make sure to delete other java entries.**
10. Click OK.
11. Close all other windows.
12. Open CMD.
13. Navigate to directory of where JNoexsClient.jar is located (Example: cd C:\Downloads\JNoexsClient)
14. Type java -jar JNoexsClient.jar

Hope this helps.

**Comment by rushairer** [comment]
> I had lots of problems when I tried it. Java 11 does not work with opening the client.
> Go [HERE](https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase10-4425482.html) to get Java SE Development Kit 10.0.2.
> For Win 10:
> 
> 1. Install jdk-10.0.2_windows-x64_bin.exe
> 2. Open Control Panel
> 3. Click on System
> 4. Click on Advance system settings on the left side
> 5. Click on Environment Variables.
> 6. Select Path in System Variables.
> 7. Click on Edit.
> 8. Click on New
> 9. Type in directory of Java 10.0.2 bin (Example: Mine is C:\Program Files\Java\jre-10.0.2\bin)
>    **Note: Make sure to delete other java entries.**
> 10. Click OK.
> 11. Close all other windows.
> 12. Open CMD.
> 13. Navigate to directory of where JNoexsClient.jar is located (Example: cd C:\Downloads\JNoexsClient)
> 14. Type java -jar JNoexsClient.jar
> 
> Hope this helps.

Thanks a lot!

**Comment by mdbell** [comment]
Yeah java 11 is currently unsupported, but it seems you sorted it out. May I ask why this issue was reopened?

**Comment by rushairer** [comment]
@mdbell  Because this problem is not fixed yet.

I download JDK10, it works. But this problem is not fixed yet.

**Comment by mdbell** [comment]
The readme says java 10, so it would be safe to assume that any issue encountered with any other versions would be because you're using another version. Anyways I'm closing the issue for now, I'll reopen if/when we decide to switch to 11 I'll reopen it
