### ISSUE TITLE
I try to write a USB connection, but it does not work well...

### ISSUE THREAD

**Issue by rushairer** [mdbell/Noexes#23]
https://github.com/rushairer/Noexes/blob/usb/server/source/noexs/source/usb.cpp

I get right idProduct
```
0x057e: 0x3000
```

but the interface index is 0, READ_ENDPOINT is 0x81 , WRITE_ENDPOINT is 0x01, it that right?

**Comment by rushairer** [comment]
```
Bus 020 Device 010: ID 057e:3000

Configuration Descriptor:
  bLength                  9
  bDescriptorType          2
  wTotalLength            32
  bNumInterfaces           1
  bConfigurationValue      1
  iConfiguration           0
  bmAttributes          0xc0
    Self Powered
  bMaxPower              500mA


Interface Descriptor:
  bLength                  9
  bDescriptorType          4
  bInterfaceNumber         0
  bAlternateSetting        0
  bNumEndpoints            2
  bInterfaceClass        255 Vendor-specific
  bInterfaceSubClass     255
  bInterfaceProtocol     255
  iInterface               0

endpoints  0 => 1, 1 =>  -127
```
When runing at Debugger.java line 57, throw a exception :

```
javax.usb.UsbPlatformException: USB error 8: Transfer error on bulk endpoint: Overflow

```

**Comment by mdbell** [comment]
Awesome to see someone helping out with Noexes! All the client sided usb code I wrote is actually untested right now, and besides the vendor ID and product IDs they were borrowed from the usb4java examples. I unfortunately can't look I to it right now (besides feedback) as I'm having some problems with my PC, and I won't have new hardware till the end of this week.

**Comment by mdbell** [comment]
Actually, in Usb connection.java I have wrong endpoint IDs (going by your lsusb stuff)

ENDPOINT_READ should be 0x80
ENDPOINT_WRITE should be 0x00

**Comment by rushairer** [comment]
read = iface.getUsbEndpoint(READ_ENDPOINT);   
if  0x80 get null


write = iface.getUsbEndpoint(WRITE_ENDPOINT); 
 if 0x00 get null

**Comment by mdbell** [comment]
That is possible but, I've also only had limited exposure with interfacing with usb devices and I've probably initialized it wrong client sided.

**Comment by mdbell** [comment]
Andi think I have your endpoints wrong .. try setting READ to 0x81 and WRITE to 0x01

**Comment by rushairer** [comment]
I tried https://github.com/jakibaki/sys-netcheat, It search from memory of switch.
It's a faster way than Noexs.

**Comment by mdbell** [comment]
Please try to stay on topic when talking about issues, and yeah it is faster to search console sided, however it also creates more overhead on the console. Noexes was designed to be as small and non-invasive as possible.

**Comment by joicoss** [comment]
Good afternoon, thank you very much for this program in advance, I just wanted to ask if there is still no way to connect via USB.

**Comment by mdbell** [comment]
@joicoss not currently, please follow issue #5 for when/if it get's implemented
