### ISSUE TITLE
TCPGecko Already Attached

### ISSUE THREAD

**Issue by ok2gogit** [mdbell/Noexes#26]
Whenever I try to attach the process, I get this error:

Module:TCPGecko
Desc: Already Attached

Trying to Detach it return "Not Attached"

Obviously, trying to search something return Desc 114...

Firmware 6.2.0, happens on every Title ID.

**Comment by DNA-Trainer** [comment]
Do you use atmosphere witch cheat support? If so, you have to turn off dmnt:cht or, as I do, 
you can hold down the L button, while you start the game. Otherwise dmnt:cht is always attached to the
process.

**Comment by trueicecold** [comment]
Thanks @DNA-Trainer, that did the trick! (I opened the issue from the wrong user earlier :))

**Comment by Darkztar** [comment]
I try to use JNoex on SX OS and having there the same problem and no option to deactivate dmnt:cht 

Any solution for this?

**Comment by masagrator** [comment]
SX OS doesn't have dmnt:cht...

**Comment by Darkztar** [comment]
> SX OS doesn't have dmnt:cht...

I know, I mean the equivalent...

How I can start a game in SX OS without that the cheat process will be started automatically
