### ISSUE TITLE
Error: Could not find or load main class me.mdbell.noexs.ui.NoexsApplication with JDK 11

### ISSUE THREAD

**Issue by mrbob312** [mdbell/Noexes#27]
this has been an issue before but now you cant download java 10 anymore so i created this issue.

i get this error when opening it on jdk 12 and 11:

`Error: Could not find or load main class me.mdbell.noexs.ui.NoexsApplication
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application`

**Comment by luiscesjr** [comment]
I believe you must download and manually configure the path when using Java 11, as described here:

https://gbatemp.net/threads/noexs-remote-debugger.512668/page-13

And well, as I said on another answer, I still believe the easier solution is to just install Java 10 JRE (Not JDK) from this lnk https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase10-4425482.html while noexes is not updated to java 11/12/13 whataver new java version is out there.

And here I'm assuming you don't have JavaFx installed, java.lang.NoClassDefFoundError could be from other problems as well, but as an advice, go for the easier solutions above first.

**Comment by ignasurba** [comment]
Solved this issue with JavaFX SDK from https://gluonhq.com/products/javafx/

> `java --module-path C:\javafx\lib --add-modules=javafx.controls,javafx.fxml -jar JNoexsClient.jar`

Works with OpenJDK 11 LTS
