### ISSUE TITLE
Failure to load firmware

### ISSUE THREAD

**Issue by Nomercyman1** [mdbell/Noexes#28]
When trying to launch noexes from the Hecate boot screen, first it said it failed to load pkg1.  After some searching around, I found someone who had posted additional lines for the hecate_ipl.ini file in the bootloader. It now shows as:
~~~~~~~~~~~~~~~~~~~~~
[Noexes]
debugmode=1
kip1=modules/kips/loader.kip
kip1=modules/kips/sm.kip
kip1=modules/kips/noexs.kip1
kip1=modules/kips/nx-dreport.kip
~~~~~~~~~~~~~~~~~~~~~~~~
All of this is in the 
~~~~~~~~~~~~~~~~~~~
{-- Custom Firmwares --}
{ }
~~~~~~~~~~~~~~~~~~~~~
Section of the .ini file, below my [CFW] lines.
Now, it simply says it failed to load firmware. I have the noexs.kip1 in my SD's root folder.

i.e
~~~~~~~~~~~~~~~~~~
{-- Custom Firmwares --}
[CFW]
........................................
[Noexes]
debugmode=1
kip1=modules/kips/loader.kip
kip1=modules/kips/sm.kip
kip1=modules/kips/noexs.kip1
kip1=modules/kips/nx-dreport.kip
{ }
~~~~~~~~~~~~~~~~~~~~~~~~~~

Please help!

**Comment by drapolas** [comment]
don't active sys-netcheat
try this to put this. (dont believe change path where you put noexs.kip1)
don't put debugmode=1

{-------- Noexs -------}
[Noexs]
fss0=atmosphere/fusee-secondary.bin
kip1=modules/noexs/noexs.kip1
kip1patch=nosigchk
logopath=bootloader/bootlogo.bmp
atmosphere=1
{ }

**Comment by mdbell** [comment]
Most likely you just had an outdated version of Hekate, try updating it
