### ISSUE TITLE
"Unable to connect"

### ISSUE THREAD

**Issue by wilhitewarrior** [mdbell/Noexes#29]
I'm not sure what I'm doing wrong on this one. I have noexs.kip1 on the root of my SD card, boot the profile through hekate then when it sends me back to hekate I load atmosphere. My hekate_ipl.ini looks like this:

[config]
autoboot=0
autoboot_list=0
bootwait=3
verification=1
backlight=100
autohosoff=0
autonogc=1

[Noexes]
debugmode=1
kip1=noexs.kip1

after I do all that, I try connecting but it doesn't work. I can connect to my FTP fine but jnoexs won't connect at all. Any help here?

**Comment by Bappsack** [comment]
Kips are in atmosphere/kips/
Not in root.

wilhitewarrior <notifications@github.com> schrieb am Mo., 27. Mai 2019,
11:47:

**Comment by wilhitewarrior** [comment]
boy do i feel dumb. lol thanks, that got it working :)
