### ISSUE TITLE
Fails to search

### ISSUE THREAD

**Issue by RubberDuck55** [mdbell/Noexes#31]
This is what it looks like:
![image](https://user-images.githubusercontent.com/34989573/62580754-ff45ea80-b874-11e9-94af-35386a1702ca.png)
not sure what the problem is but it took me over two days to finally get this to work so I would appreciate the help.   :)

**Comment by RubberDuck55** [comment]
Also this when I try to pause search:
![image](https://user-images.githubusercontent.com/34989573/62581070-04f00000-b876-11e9-854b-545cec5b95c1.png)

**Comment by mdbell** [comment]
You need to attach to a process before trying to debug it.

**Comment by RubberDuck55** [comment]
how do I do that?
