### ISSUE TITLE
Unknown Error when trying to Attach

### ISSUE THREAD

**Issue by Smoker1** [mdbell/Noexes#34]
I make sure to hold the L Button when running the Game I want.

When the first Screen comes up, I release it. Then when I get into a area of the Game, I Pause it. Then I go to Connect it to JNoexs. I have had no Issues before until now. Now, I keep getting either.....

Gecko already being attached, but I am HOLDING THE L BUTTON!!!

Or I get this Error....

Attach Failed

Reason
Module:1
Desc:122

FW 9.1.0 | AMS 0.10.2

**Comment by mdbell** [comment]
If you're still having this issue please reach out to me and i'll reopen it. My best guess is that something is already attached to the process, most likely Atmosphere's cheat module

**Comment by Smoker1** [comment]
I am getting this on 10.0.4 using AMS 0.13.0

By all accounts, I should be able to Attach.

I Press L, and I get the 122 Error.
I HOLD the L Button, and it says TCPGecko is already Attached.

**Comment by Smoker1** [comment]
> If you're still having this issue please reach out to me and i'll reopen it. My best guess is that something is already attached to the process, most likely Atmosphere's cheat module

I am getting this on 10.0.4 using AMS 0.13.0

By all accounts, I should be able to Attach.

I Press L, and I get the 122 Error.
I HOLD the L Button, and it says TCPGecko is already Attached.

**Comment by mdbell** [comment]
What game? Do you have any other system modules loaded? Can you take a screenshot of the error screen?

**Comment by mdbell** [comment]
Closing this issue as due to lack of response. Please let me know if you still have the problem and I'll reopen it!
