### ISSUE TITLE
Error On MacOS + Java 10.0.2 

### ISSUE THREAD

**Issue by Blackbird12621** [mdbell/Noexes#35]
Hy,
I getting a error:

Error: Could not find or load main class me.mdbell.noexs.ui.NoexsApplication
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

When I manually add javafx the error changes to

Error: Could not find or load main class JNoexsClient.jar
Caused by: java.lang.ClassNotFoundException: JNoexsClient.jar

I have installed Java 10.0.2 and am using macOS.
Thanks for the help.

**Comment by nbcsteveb** [comment]
Download latest Java FX SDK from https://gluonhq.com/products/javafx/ then try:

```
java --module-path /opt/javafx-sdk-15.0.1/lib --add-modules=javafx.controls,javafx.fxml -jar ./JNoexsClient.jar
```

**Comment by haykuro** [comment]
Download latest Java FX SDK from https://gluonhq.com/products/javafx/ then try:

```
java --module-path /opt/javafx-sdk-15.0.1/lib --add-modules=javafx.controls,javafx.fxml -jar ./JNoexsClient.jar
```

**Comment by mdbell** [comment]
CLosing this issue due to no response. If you're still having trouble please open a new one!
