### ISSUE TITLE
Noexes uses a reserved program ID which will eventually conflict with Atmosphere.

### ISSUE THREAD

**Issue by SciresM** [mdbell/Noexes#37]
Noexes is currently using program ID 0100000000000038; this is the program ID of the official profiler sysmodule, which provides the `banana` service used for profiling games.

In the future, Atmosphere will re-implement this system module, using its ID.

This will break noexes and cause atmosphere to fail to launch when noexes is installed.

Noexes probably wants to change its program ID to not use one that's used by an official hos program, since it's not reimplementing the program in question.

**Comment by mdbell** [comment]
Thank you for the heads up! Just pushed a change to address the title IDs, as well as rebuilt the kip module.
