### ISSUE TITLE
java.io.IO Exception error 

### ISSUE THREAD

**Issue by zeldablade7** [mdbell/Noexes#38]
I've been getting this error every time I press the search button on the program. Keep in mind that I'm able to add a PID to the program just fine. Just can't do anything else.
![image](https://user-images.githubusercontent.com/53205276/86372459-cb6f7280-bc47-11ea-89d4-c82c23fc2270.png)

**Comment by mdbell** [comment]
Where do you have the client saved? It most likely can't create the file for the memory dump in the current directory.

**Comment by zeldablade7** [comment]
I have it on an external hard drive

**Comment by zeldablade7** [comment]
If you're wondering, I'm using the release build, not the master build

**Comment by mdbell** [comment]
Could you try running it from your system drive? Perhaps your desktop?

**Comment by zeldablade7** [comment]
I tried that and it didn't work

**Comment by zeldablade7** [comment]
I think I fixed the problem.  :)

**Comment by mdbell** [comment]
Can you elaborate on how? Incase anyone else runs into the same problem I can direct them here
