### ISSUE TITLE
USB support?  Is noexes still working at all?

### ISSUE THREAD

**Issue by ThePsycrow** [mdbell/Noexes#41]
I used this in 2019 but am not comfortable doing it through the network method, interested in the USB option if it's ever implemented.  Unless there's something else out there that can do that?
I don't know if noexes still works at all though, I haven't tried in over a year.

**Comment by ValiantStorm** [comment]
USB is likely broken on 10.X and above, due to changes in the Switch's OS.

**Comment by masagrator** [comment]
Usb never worked.

**Comment by mdbell** [comment]
USB hasn't been implemented yet, please see issue #5
