### ISSUE TITLE
JNoexs can’t connect to Switch 12.0.0

### ISSUE THREAD

**Issue by nomo9133** [mdbell/Noexes#42]
my system is 12.0.0 with Atmosphere 0.19.1, Noexs 1.1.2, my computer has installed JAVA 10 and it is running normally, but I cannot connect JNoexs to the switch, I have already selected Noexs in launch , Without any errors.
Can anyone know how to solve it?

**Comment by Manu098vm** [comment]
I'm using the tomvita fork compiled with the latest libnx. The zip has been shared by Berichan in the PKHeX Dev discord server: https://cdn.discordapp.com/attachments/699129031911800872/833390870345547846/noexes_sys_tomvita.zip

Works fine for me on 12.0 AMS 19.1.

**Comment by mdbell** [comment]
Once I get a dev environment setup I'll rebuild Noexes and look into this! Going by @Manu098vm response I should onl'y need to rebuild with a newer version of libnx

**Comment by Mysterious-20** [comment]
i having a trouble connecting my switch to jnoexes will somebody help please?
