### ISSUE TITLE
issues with loading the main class on newer java versions.

### ISSUE THREAD

**Issue by monkeyman4412** [mdbell/Noexes#45]
Java 10 specifically is pretty much impossible to get through oracle. as their archive is just not working, and java 10 is no longer supported. On later Java versions such as 11 and 16. It fails to load the main class. The error provided 
"Error: Could not find or load main class me.mdbell.noexs.ui.NoexsApplication
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application"
this is running java version 16.0.1

**Comment by ObscenityIB** [comment]
Dont know why this issue is closed.
Its still valid, Java 10 just simply doesnt exist anymore.

**Comment by monkeyman4412** [comment]
> 
> 
> Dont know why this issue is closed. Its still valid, Java 10 just simply doesnt exist anymore.

I closed it since they already have a high priority issue to switch to a new java version
#24
