### ISSUE TITLE
Breakpoint support

### ISSUE THREAD

**Issue by MarioPossamato** [mdbell/Noexes#46]
So, it seems as though hardware breakpoints have some support in the server and the java client, however the java client, to my knowledge, doesn't expose any means of using it.  There's a rudimentary hardware breakpoint feature [here](https://github.com/mdbell/Noexes/blob/556184d74d2558ff916acd2fdd8de06cc53b20ca/server/source/noexs/source/debug.cpp#L102), as well as some other code in the java client.  In a general sense, what would be needed to set a breakpoint, and would adding support for setting breakpoints in the java client be possible?

**Comment by masagrator** [comment]
Hardware breakpoints and watchpoints are part of Atmosphere's ongoing tma2 reimplementation btw.

https://github.com/Atmosphere-NX/Atmosphere/pull/1405

**Comment by MarioPossamato** [comment]
Ah, I didn't know that; thanks for the info! :)
