### ISSUE TITLE
Implement Float value display and search

### ISSUE THREAD

**Issue by AnalogMan151** [mdbell/Noexes#6]
Add float option to types searchable and auto convert float values to hexadecimal for poking and freezing.

**Comment by mdbell** [comment]
Just a quick update on this issue: The biggest problem for this is dealing with floating point errors, and I'd have to rework the UI a bit. It is currently planned to be done, till then I recommend doing greater/less then searches!

**Comment by igromanru** [comment]
Wow, almost one year passed, still no float support. Sad :(

**Comment by igromanru** [comment]
May I ask why have you closed the issue? If I see it right, the float support is still missing.
And it's actually a pretty important features, since many games use float for money, HP etc.

**Comment by mdbell** [comment]
Floating point error makes it difficult to search for exact values, instead just convert it to hex and use a grater then/less then search. If you (or anyone else) can come up with an elegant way to search for floats and makes a pull request I'll gladly accept it

**Comment by igromanru** [comment]
I understand, but is it not better to let the issue open? So people can see that it's still a problem?
